% !TEX encoding = UTF-8 Unicode
\documentclass[11pt,spanish]{article}
\usepackage[spanish,mexico]{babel}
\usepackage[utf8]{inputenc}
\usepackage{authblk}
\usepackage{setspace}
\usepackage[margin=1.25in]{geometry}
\usepackage{graphicx}
\usepackage{subcaption}
\usepackage{amsmath}


%%%%%% Bibliography %%%%%%
% Replace "sample" in the \addbibresource line below with the name of your .bib file.
\usepackage[style=ieee, 
citestyle=numeric-comp,
sorting=none]{biblatex}
\addbibresource{sample.bib}

%%%%%% Title %%%%%%
% Full titles can be a maximum of 200 characters, including spaces. 
% Title Format: Use title case, capitalizing the first letter of each word, except for certain small words, such as articles and short prepositions
\title{Análisis de Supervivencia de fallas del corazón}

%%%%%% Authors %%%%%%
\author{Alfie González, Santiago Battezzati \& Elena Villalobos.}

%%%%%% Affiliations %%%%%%
\affil{Maestría en Ciencia de datos}
\affil{Instituto Tecnológico Autónomo de México}

%%%%%% Date %%%%%%
% Date is optional
\date{27 de Mayo, 2021}

%%%%%% Spacing %%%%%%
% Use paragraph spacing of 1.5 or 2 (for double spacing, use command \doublespacing)
\onehalfspacing

\begin{document}

\maketitle

%%%%%% Main Text %%%%%%

\section{Introducción}

Las fallas del corazón son de las muertes más comunes


% \begin{table}[b]
%     \caption{This is an example table.}    
%     \centering
%     \begin{tabular}{ccc}
%             \hline
%             Column 1 & Column 2 & Column 3 \\  
%             \hline
%             Cell 1 & Cell 2 & Cell 3\\ 
%             Cell 4 & Cell 5 & Cell 6 \\
%             \hline
%             \end{tabular}
% 
%     \label{tab:1}
% \end{table}

\section{Results}
The results should describe the experiments performed and the findings observed. The results section should be divided into subsections to delineate different experimental themes. Subheadings should either be all phrases or all complete sentences. All data must be shown either in the main text or in the Supplementary Materials.  
\begin{itemize}
    \item All data, both that in the main part of the manuscript and that in the Supplementary Materials, should be presented in the Results. No data should be presented for the first time in the Discussion. Data (such as from Western blots) should be appropriately quantified from multiple independent experiments. Inclusion of biological data from individual experiments that have not been repeated at least twice is generally not permitted.
    \item Subheadings must be either all complete sentences or all phrases. They should be brief, ideally less than 10 words. Subheadings should not end in a period. The Results section may have as many level 1 subheadings as are necessary.
    \item Figures and tables must be called out in numerical order. For example, the first mention of any panel of Figure 3 cannot precede the first mention of all panels of Figure 2. The supplementary figures (for example, Figure S1) and tables (Table S1) must also be called out in numerical order. All figures and tables should have a title and a legend.
    \item Mathematical expressions within a sentence of text should be created with ordinary Word characters; if this is not possible, then use MathType (or the equivalent). Only use MathType when necessary — for example, characters with overbars or carets, with stacked superscripts and subscripts, or within square root symbols.
\end{itemize}

\section{Discussion}
Include a Discussion that summarizes (but does not merely repeat) your conclusions and elaborates on their implications. There should be a paragraph outlining the limitations of your results and interpretation, as well as a discussion of the steps that need to be taken for the findings to be applied. Please avoid claims of priority. 

\section{Materials and Methods}
The materials and methods section should provide sufficient information to allow replication of the results. This section should be broken up by subheadings. Under exceptional circumstances, when a particularly lengthy description is required, a portion of the materials and methods can be included in the Supplementary Materials. 

\subsection{Experimental and Technical Design}
Begin the Materials and Methods with a subsection titled “Experimental and Technical Design” describing the objectives and design of the study.  If applicable, include a diagram or flowchart of the entire experimental design to illustrate the most important elements, such as specific materials, treatments, measurements, data collection, and methods of data analysis. This will facilitate the ability of editors, reviewers, and readers to understand and follow the concept of the study, the study design, and the results. 

\subsection{Subsection 1…n}
The rest of the Material and Methods should be divided by short subheadings for each method or technique. When a particularly lengthy description is required, a portion of the materials and methods can be included in the Supplementary Materials. This option should be used only in exceptional circumstances.

\subsection{Animal and Human Studies}
Studies involving animals or humans should include separate sections with the subheadings “Animals and Study Approval” or “Subjects and Study Approval,” as appropriate for animal or human research, respectively. All human studies must have been approved by the appropriate institutional review board(s). The Subjects and Study Approval subsection must include a specific declaration of such approval, including a statement indicating that written informed consent was received from participants prior to inclusion in the study. For animal models, the Animals and Study Approval subsection must include the precise genotype, strain, source, number of backcrosses, sex, and age of animals. Additionally, all animal studies must have been approved by the appropriate institutional review board(s). This subsection must include a specific declaration of such approval.

\subsection{Statistical Analysis}
The final subsection of the Materials and Methods should be titled “Statistical Analysis.”  This subsection describes the statistical methods with enough detail for verification of the results by a knowledgeable reader with access to the original data. Although this subsection describes the statistical methods used, the values for N, P, and the specific statistical test performed for each experiment should be included in the appropriate figure or table legend or main text. 

\section*{Acknowledgments}
Anyone who made a contribution to the research or manuscript, but who is not a listed author, should be acknowledged (with their permission). Types of acknowledgements include:

\subsection*{General} 
Thank others for any contributions, whether it be direct technical help or indirect assistance 

\subsection*{Author Contributions} 
Describe contributions of each author to the paper, using the first initial and full last name. 

\medskip Examples:

``S. Zhang conceived the idea and designed the experiments.''

``E. F. Mustermann and J. F. Smith conducted the experiments.''

``All authors contributed equally to the writing of the manuscript.''

\subsection*{Funding}
Name financially supporting bodies (written out in full), followed by the funding awardee and associated grant numbers (if applicable) in square brackets. 

\medskip Example: 

``This work was supported by the Engineering and Physical Sciences Research Council [grant numbers xxxx, yyyy]; the National Science Foundation [grant number zzzz]; and a Leverhulme Trust Research Project Grant.'' 

\medskip
If the research did not receive specific funding, but was performed as part of the employment of the authors, please name this employer. If the funder was involved in the manuscript writing, editing, approval, or decision to publish, please declare this.

\subsection*{Conflicts of Interest}
Conflicts of interest (COIs, also known as ``competing interests'') occur when issues outside research could be reasonably perceived to affect the neutrality or objectivity of the work or its assessment. 

Authors must declare all potential interests – whether or not they actually had an influence – in a ‘Conflicts of Interest’ section, which should explain why the interest may be a conflict. Authors must declare current or recent funding (including for Article Processing Charges) and other payments, goods or services that might influence the work. All funding, whether a conflict or not, must be declared in a ``Funding Statement.'' The involvement of anyone other than the authors who 1) has an interest in the outcome of the work; 2) is affiliated to an organization with such an interest; or 3) was employed or paid by a funder, in the commissioning, conception, planning, design, conduct, or analysis of the work, the preparation or editing of the manuscript, or the decision to publish must be declared.

If there are none, the authors should state ``The author(s) declare(s) that there is no conflict of interest regarding the publication of this article.'' Submitting authors are responsible for coauthors declaring their interests. Declared conflicts of interest will be considered by the editor and reviewers and included in the published article.

\subsection*{Data Availability}
A data availability statement is compulsory for all research articles. This statement describes whether and how others can access the data supporting the findings of the paper, including 1) what the nature of the data is, 2) where the data can be accessed, and 3) any restrictions on data access and why.

If data are in an archive, include the accession number or a placeholder for it. Also include any materials that must be obtained through a Material Transfer Agreements (MTA). 


\end{document}
